:scheduler:
  :schedule:
    hello_world:
      cron: "*/1 * * * *"
      class: HelloWorldJob

      # run every minute of every hour, every day of the month, every month, every day of the week
      # refer to https://crontab.guru/
